### PR TITLE
Fix version split with Git refs

### LINKED ISSUE #9: Parser::splitVersionString does not handle Git URLs used as dependencies/versions correctly
Currently the description of `Parser::splitVersionString` reads:

> To avoid splitting on scoped package-names, every but the last @ are considered package name.

This does not suffice when it comes to Git URLs used as dependencies/versions which themselves may contain @ to separate user (or credentials in general) from host/rest.

Cf. https://docs.npmjs.com/cli/v10/configuring-npm/package-json#git-urls-as-dependencies

Consider the following examples:
- `@foo/bar@git+ssh://user@host:1234/foo/bar#semver:^1.2.3` should be split into `@foo/bar` and `^1.2.3`
- `@foo/bar@git://user@host/foo/bar.git#v1.2.3` should be split into `@foo/bar` and `v1.2.3`

Suggested fix:
```php
public static function splitVersionString($versionString)
{
    // Scoped package names start with an "@" → skip the first character.
    // Note: $versionString may contain even more than two "@" if version is "protocol://user@host..."
    $location = strpos($versionString, '@', 1);
    if ($location > 0) {
        $name = substr($versionString, 0, $location);
        $version = substr($versionString, $location + 1);
        // Handle special cases that package.json allows for "Git URLs as Dependencies"
        if (preg_match('/#(semver:)?(.+)$/', $version, $matches) === 1) {
            $version = $matches[2];
        }
        return [$name, $version];
    }
    throw new \InvalidArgumentException('Version string is expected to contain "@" separating name from version.');
}
```

### PR DESCRIPTION
**Pull request by InvisibleSmiley**
Fixes #9.

### CODE REVIEW

**Comment by InvisibleSmiley** [comment]
FTR I refrained from doing cleanup here even though I had a strong urge to do it (e.g. replace static:: by self::).
After all it's not my project and not the scope of this PR either. ;-)

File: src/Parser.php [hunk 1]
```diff
@@ -216,20 +216,28 @@ function ($e) {
...
+            $prefix = '@';
+            $rest = substr($versionString, 1);
+        } else {
+            $prefix = '';
+            $rest = $versionString;
+        }
+
+        $atPos = strpos($rest, '@');
+        if ($atPos === 0 || $atPos === false) {
+            throw new ParserException('Invalid version string: ' . $versionString);
```
Comment (PRGfx) [inline src/Parser.php]: Could you please add a code to the exception as for the other ones, for easier identification, usually the current timestamp.

File: src/Parser.php [hunk 2]
```diff
@@ -216,20 +216,28 @@ function ($e) {
...
      */
     public static function splitVersionString($versionString)
     {
-         $parts = explode('@', $versionString);
-         $version = array_pop($parts);
-         return [
-             implode('@', $parts),
-             $version
-         ];
+        if (strpos($versionString, '@') === 0) {
```
Comment (PRGfx) [inline src/Parser.php]: I preferred your original suggestion with the `strpos` with offset 1 – it either skips the namespace @ or it should work for single-letter package names with a result of 0 and was less noise imo.

File: tests/src/Unit/ParserTest.php [hunk 3]
```diff
@@ -231,6 +233,21 @@ public function testVersionSplitting()
...
+
+        static::assertSame(
+            ['@foo/bar', 'git://user@host/foo/bar.git#v1.2.3'],
+            Parser::splitVersionString('@foo/bar@git://user@host/foo/bar.git#v1.2.3')
+        );
+
+        static::assertSame(
+            ['@foo/bar', 'file:vendor/foo/bar'],
+            Parser::splitVersionString('@foo/bar@file:vendor/foo/bar')
+        );
```
Comment (PRGfx) [inline tests/src/Unit/ParserTest.php]: Could you please add an example with a non-namespaced package for completeness?

If you prefer, you can also restructure this to use a PHPUnit dataprovider function.

**Review by PRGfx — CHANGES_REQUESTED** [review]
Thank you for the pull request. I would appreciate it if you could go over the remarks.

File: src/Parser.php (hunk 1 above)
Comment (InvisibleSmiley) [reply src/Parser.php]: Done, but only to restore consistency.
I recommend to remove those in the future though since I feel they offer no real benefit.
Exception types should be separated by exception name, grouped by interfaces, and provide details by message and possibly further properties (public, or exposed via getters).
Just my 2c
